---
- name: Copy the network config file
  template: 
    src: "templates/ifcfg"
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{card_name}}"
    backup: yes

- name: fetch network config file
  fetch:
    src: "/etc/sysconfig/network-scripts/ifcfg-{{card_name}}"
    dest: /tmp/
    
# - name: restart network
#   service: 
#     name: network
#     state: restarted
#     enabled: yes

