---
# tasks file for keepalived_proxy_install
- name: install
  shell: yum install keepalived -y

- name: add script
  copy: src="mysql.sh" dest="/etc/keepalived/mysql.sh" owner=root group=root mode=0755

- name: add script
  copy: src="zabbix_server.sh" dest="/etc/keepalived/zabbix_server.sh" owner=root group=root mode=0755

- name: config master
  template: src="templates/keepalived_master.conf.j2" dest="/etc/keepalived/keepalived.conf" owner=root group=root mode=0644
  run_once: true
  delegate_to: "{{master_ip}}"

- name: config backup
  template: src="templates/keepalived_backup.conf.j2" dest="/etc/keepalived/keepalived.conf" owner=root group=root mode=0644
  run_once: true
  delegate_to: "{{backup_ip}}"

- name: start
  shell: systemctl start keepalived
