{
 "title": "Cluster Hardware Summary",
 "tags": [ "Daily" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataCenter", "label": "DataCenter", "query": "prometheus" },
   { "name": "CPU", "label": "CPU", "query": "*" },
   { "name": "Memory", "label": "Memory", "query": "*" },
   { "name": "DiskSpace", "query": "*" },
   { "name": "TopK", "label": "TopK", "query": "10" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_exporter_build_info,instance)"
   }
  ]
 },
 "panels": [
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Free Space For Each Partition",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    },
    {}
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Application Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{instance=~\"10.0.40.*\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SwapCached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_VmallocUsed_bytes )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CPU Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Load5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($TopK,node_load5{instance=~\"10.0.40.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "NetWork", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Network Traffic In",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($TopK,irate(node_network_receive_bytes_total{device!~\"em.*|p4p1\",instance=~\"10.0.40.*\"}[5m])*8)",
     "legendFormat": "{{instance}} {{device}} _in"
    }
   ]
  },
  {
   "title": "Network Traffic Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "topk($TopK,irate(node_network_transmit_bytes_total{device!~\"em.*|p4p1\",instance=~\"10.0.40.*\"}[5m])*8)",
     "legendFormat": "{{instance}} {{device}} _out"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "IOPS Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "iops", "label": "Reads I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdb\",instance=~\"10.0.40.*\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOPS Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "iops", "label": "Writes I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "topk($TopK,irate(node_disk_writes_completed_total{device=\"sdb\",instance=~\"10.0.40.*\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  }
 ]
}