{
 "title": "k19",
 "tags": [
  "node_exporter ",
  "StarsL.cn",
  "Prometheus "
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "device",
    "label": "网卡",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   {
    "name": "maxmount",
    "label": "最大挂载目录",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "show_hostname",
    "label": "展示使用的主机名",
    "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$node\"}, nodename)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage Avg",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg((1-(node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100)"
    }
   ]
  },
  {
   "title": "Memory Usage  Max",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "avg((1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100)"
    }
   ]
  },
  {
   "title": "Memory Usage Min",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "avg((1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100)"
    }
   ]
  },
  {
   "title": "CPU load5 Avg",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "targets": [
    { "expr": "avg((node_load5))" }
   ]
  },
  {
   "title": "CPU load5 Max",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "targets": [
    { "expr": "avg((node_load5))" }
   ]
  },
  {
   "title": "CPU load5 Min",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    { "expr": "avg((node_load5))" }
   ]
  },
  {
   "title": "System disk Avg",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg((node_filesystem_size_bytes{mountpoint=\"/\"}-node_filesystem_free_bytes{mountpoint=\"/\"}) *100/(node_filesystem_avail_bytes {mountpoint=\"/\"}+(node_filesystem_size_bytes{mountpoint=\"/\"}-node_filesystem_free_bytes{mountpoint=\"/\"})))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "System disk Max",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "avg((node_filesystem_size_bytes{mountpoint=\"/\"}-node_filesystem_free_bytes{mountpoint=\"/\"}) *100/(node_filesystem_avail_bytes {mountpoint=\"/\"}+(node_filesystem_size_bytes{mountpoint=\"/\"}-node_filesystem_free_bytes{mountpoint=\"/\"})))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "System disk Min",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "avg((node_filesystem_size_bytes{mountpoint=\"/\"}-node_filesystem_free_bytes{mountpoint=\"/\"}) *100/(node_filesystem_avail_bytes {mountpoint=\"/\"}+(node_filesystem_size_bytes{mountpoint=\"/\"}-node_filesystem_free_bytes{mountpoint=\"/\"})))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Data disk Avg",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg((node_filesystem_size_bytes{mountpoint=\"/opt\"}-node_filesystem_free_bytes{mountpoint=\"/opt\"}) *100/(node_filesystem_avail_bytes {mountpoint=\"/opt\"}+(node_filesystem_size_bytes{mountpoint=\"/opt\"}-node_filesystem_free_bytes{mountpoint=\"/opt\"})))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Data disk Max",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "avg((node_filesystem_size_bytes{mountpoint=\"/opt\"}-node_filesystem_free_bytes{mountpoint=\"/opt\"}) *100/(node_filesystem_avail_bytes {mountpoint=\"/opt\"}+(node_filesystem_size_bytes{mountpoint=\"/opt\"}-node_filesystem_free_bytes{mountpoint=\"/opt\"})))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Data disk Min",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "avg((node_filesystem_size_bytes{mountpoint=\"/opt\"}-node_filesystem_free_bytes{mountpoint=\"/opt\"}) *100/(node_filesystem_avail_bytes {mountpoint=\"/opt\"}+(node_filesystem_size_bytes{mountpoint=\"/opt\"}-node_filesystem_free_bytes{mountpoint=\"/opt\"})))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  }
 ]
}