# install pushgateway
- name: unpack the pushgateway file
  unarchive: src=/opt/software_package/componet/pushgateway-1.0.1.linux-amd64.tar.gz dest=/opt copy=yes

- name: create link
  file:
   src: /opt/pushgateway-1.0.1.linux-amd64
   dest: /opt/pushgateway
   state: link

- name: run pushgateway
  shell: nohup /opt/pushgateway/pushgateway &

- name: Check if pushgateway is accessible
  uri:
    url: http://{{hostvars[inventory_hostname].ansible_default_ipv4.address}}:9091
    method: GET
    status_code: 200


