- name: Install zookeeper
  hosts: kafka_zk
  remote_user: root
  roles:
  - zookeeper_install
  tags: zookeeper_install

- name: Install kafka
  hosts: kafka_hosts
  remote_user: root
  roles:
  - kafka_install
  tags: kafka_install

