---
# tasks file for java_install
- name: unpack the jdk file
  unarchive: src={{all.files}}/{{jdk.file}} dest={{jdk.dir}} copy=yes
- name: ln -s
  shell: ln -s {{jdk.dir}}/{{jdk.version}} {{jdk.dir}}/jdk
- name: install config file
  template: src=java.sh dest=/etc/profile.d/
- name: source java profile
  shell: source /etc/profile.d/java.sh
- name: java -version
  shell: |
    source /etc/profile
    java -version
  register: result
- name: Show debug info
  debug: var=result verbosity=0