start_user: "prometheus"
exec_file: "/opt/prometheus/prometheus"
config_file: "/opt/prometheus/prometheus.yml"
tsdb_path: "/data1/prometheus"
prometheus_version: "prometheus-2.12.0.linux-amd64"
# web_uri_configs: '["172.24.9.50:9090"]'
#数据过期时间
data_retention_time: 30d


