---
# tasks file for kafkamanager_install
- name: scp the file
  unarchive: src={{all.files}}/{{kafkamanager.file}} dest={{kafkamanager.dir}}/ copy=yes
- name: create soft link
  file: path={{kafkamanager.dir}}/kafka-manager state=link src={{kafkamanager.dir}}/{{kafkamanager.version}}
- name: create user
  shell: useradd kafka-manager
- name: config kafka-manager
  template: src="application.conf" dest="{{kafkamanager.dir}}/{{kafkamanager.version}}/conf/application.conf" owner=kafka-manager group=kafka-manager mode=0644
- name: chown
  shell: |
    chown kafka-manager:kafka-manager -R {{kafkamanager.dir}}/{{kafkamanager.version}}
    chown kafka-manager:kafka-manager -R {{kafkamanager.dir}}/kafka-manager
- name: start
  shell: su - kafka-manager -c "nohup {{kafkamanager.dir}}/kafka-manager/bin/kafka-manager -Dconfig.file={{kafkamanager.dir}}/kafka-manager/conf/application.conf -Dhttp.port=23333 &"
- name: Check if Kafka-manager is accessible
  wait_for:
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    port: 23333
    state: started
    delay: 10
    #timeout时间一定要大于上面的delay时间，否则会出现错误的检测结果
    timeout: 15
    connect_timeout: 5



