---
# tasks file for prometheus_install
- name: unpack the node_export file
  unarchive: src={{all.files}}/{{node_exporter.node_exporter_version}}.tar.gz dest={{node_exporter.dir}}/ copy=yes
- name: create soft link
  file: path={{node_exporter.dir}}/node_exporter state=link src={{node_exporter.dir}}/{{node_exporter.node_exporter_version}}
- name: create user
  shell: useradd node_exporter
- name: chown
  shell: |
    chown -R node_exporter:node_exporter {{node_exporter.dir}}/{{node_exporter.node_exporter_version}}
    chown -R node_exporter:node_exporter {{node_exporter.dir}}/node_exporter

- name: add system service
  template: src="templates/node_exporter.service" dest="/etc/systemd/system/node_exporter.service" owner=root group=root mode=0644

- name: node_exporter server started
  service:
    name: node_exporter
    enabled: true
    state: started

- name: Check if node_exporter is accessible
  uri:
    url: http://{{hostvars[inventory_hostname].ansible_default_ipv4.address}}:9100
    method: GET
    status_code: 200


