global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
  - static_configs:
    - targets:
        - 127.0.0.1:9093

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
    - targets: ['localhost:9090']
      labels:
        instance: prometheus
