---
## tasks file for zabbix-agent_install
- name: install zabbix-agent
  yum: name=zabbix-agent state=present
- name: modify zabbix-agent.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: 'Server=127.0.0.1'
    line: 'Server={{hostvars[inventory_hostname].ansible_default_ipv4.address}}'
    backrefs: yes
- name: modify zabbix-agent.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: 'ServerActive=127.0.0.1'
    line: 'ServerActive={{hostvars[inventory_hostname].ansible_default_ipv4.address}}'
    backrefs: yes
- name: modify zabbix-agent.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: 'Hostname=.*'
    line: 'Hostname={{hostname}}'
    backrefs: yes
- name: modify zabbix-agent.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: '# HostMetadataItem='
    line: 'HostMetadataItem=system.uname'
    backrefs: yes

- name: modify zabbix-agent.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: '# EnableRemoteCommands=0'
    line: 'EnableRemoteCommands=1'
    backrefs: yes

- name: modify zabbix-agent.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: 'Timeout='
    line: 'Timeout=10'
    backrefs: yes

- name: copy megacli file
  copy:
    src: "disk.conf"
    dest: "/etc/zabbix/zabbix_agentd.d"

- name: create scripts
  shell: mkdir /etc/zabbix/scripts
- name: Create a directory if it does not exist
  file:
    path: /etc/zabbix/scripts 
    state: directory
    mode: '0755'

- name: copy megacli file
  copy: 
    src: "diskcheck_megacli.sh"
    dest: "/etc/zabbix/scripts"
    mode: 0755
    
- name: systemctl restart zabbix-agent
  shell: |
    systemctl restart zabbix-agent
    systemctl enable zabbix-agent

- name: Check if zabbix-agent is accessible
  wait_for:
    port: 10050
    state: started
    delay: 10
    #timeout时间一定要大于上面的delay时间，否则会出现错误的检测结果
    timeout: 15
    connect_timeout: 5
