---
# tasks file for keepalived_proxy_install
- name: install
  shell: yum install keepalived ipvsadm -y

- name: config master
  template: src="templates/keepalived_master_{{city}}.conf.j2" dest="/etc/keepalived/keepalived.conf" owner=root group=root mode=0644
  run_once: true
  delegate_to: "{{master_ip}}"

- name: config backup
  template: src="templates/keepalived_backup_{{city}}.conf.j2" dest="/etc/keepalived/keepalived.conf" owner=root group=root mode=0644
  run_once: true
  delegate_to: "{{backup_ip}}"

- name: start
  shell: systemctl start keepalived
